language: R
sudo: false
cache: packages
warnings_are_errors: false

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
notifications:
  pushover:
    api_key:
      secure: OXBF2UvZP7aLznQfezlASvW7A5TcmEQbux0mmx01ZcdiglhB2UVKE4jkxI9qPIP0qr8piIJ3GmVNxl+lmxq7vmw3ESUzFrQVjZ6T223+zc3p3PYfPvEoyZzJvt2tH9SwxZny3h5jJGvgKbaHsiutoj047z7PNa2Wvp+eIw9jnBwp9hdFBptLr0uIY2xxfFrA9t35mb+uEMC2PtORFrQZNc585vTj9vPUesuiOyeE/O/4chNS1dWtE13NtUjY/t8pPApkgLN7EXTdsN+yg4Vqy7E/dbn5ObY+I8uPCdtCvaezLIvqAAqameqw3CtSpXDw2GQdC/FG0Q0PXbQjp/uONVeZ4rUIuhzIZ+I7lZ05e2xqWZsY+M3yL8APaZVwTI/ub9y6c6/kbceKUQycaEJatG1kJiErgXRRe3VlL1POmDoNrucAGTNU8/gsRi94NNRC2qD3Eh1w/RDP0R+Malu74MS17MSEsSwFwMaols5Foy1rSF7oYGkmSnkX6w+CDEa8Mz1DTOvbX3H7bbpGK9NBlCElmx2J+yczsgopg6MISArPpTXjwI3L/m4QRvuGeEd+sMKj06g1DYCNOp9eIt9O2o1qCa7O2TYnhMf2nDdJ2b5qbjbmKFse/Z3EOq4EfLX9EWjETro0vKfEkLtMu38WQjRZCa/UZ8FogfkG429O5SQ=
    users:
      secure: dagipcGb5/nV2fo3k6jdw/BMu41zD1OeN49ywtd8PjZNGxjk1IfJPYlivtp1Ngv54n7oRIlx/G1k8Hh4NczOCgZZGTEL+Vaj/XE0EzngLjDRMPJKWopox3/Gns91TQMSbUKP8Qjp8U/0H31Ij6MI+FKW2Bjbad+z1qRqrj27X1CQ8UPakJ1RPrCxCHuAKZgXPC2i//ax4/TrzFn1+39metGP/8oaOXdxyZClOn+y/X0DPCKQvrhwuUJegQTBAgtMfTIVt20lDl+WDHFJGri1fgG4Q3sWoEl6QWj2EUqF7bP7OaS/09neBUzsJ3maJaZVDTC8J+rIFcAuQTd9EQ8tl5l0CnFwnl8Z00VrnGO2dpeLF30dTnBJLqLThcfCKcKfhGQ3F8OGmGTGAgIGBXQdxlppAtgMNNH8IS2kaDJWvc7ceLBi/y67dkG6M43+Y8Viko7GbK+zdw7ss269XuCY38LwmwuhQo/wlgPJZ1Cls01YVFJ2tmbKfReWu2PAgAe76EvjuMb3zlj/Zqv30FGR14axjN3T84FnGs+GhjNfiKPCUDpT6Zp1V0Qfr0oUV6uMgZQ+jMTLcGYR1GGFsfRYQOSH0xF8wczck6xUsaPZLqNIcXdPiSpSULWxw5bK/b5xALXmmd7BMXxmZyxxJxOqjuXrTidx4hjxTWhVXk2d/88=
