language: R
sudo: false
cache: packages
warnings_are_errors: false

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
notifications:
  pushover:
    api_key:
      secure: 8oqk9P4rfYGZJrjlo3uTsWw2tyVvvd5eKAndF5QF/vRJo6cNzTwX15ny5jEO/ko/RQxspPWNUk93dI4HIMMQj7zf4PnfQrO4Iu3tXN/ZcybKGFVqqGje+FQSNavZl8ONY2XME4QJFDnoEoNrX1jLxPqHycK1N4x+PdTDaiy5cgstgBd7PCbk0i7Su4pJHk59etuAUTV+Osr7ANyZotT7aPc6R5Tr9gmUQHUfQRzkQfo5Fz5hVSNt6smo4WJPZ06ocGmMYRQq6iliM5EFgTrgbA4aq09+WU2793o5bZW/oedbp5Y0k9/rkpnNH4KQHEQDs50DfVo8yq31hR1a8llcqMIkQ4BjFRA3lc4TV/BYiuNJ6lTwWmZ3cDVHU8mtupYQjW5YfkPVmnNgOwLTJYdyMClM9RTcvpryca8xrIiQsdVx61I3cwsYg2anrDJeuaof7vTM1PXzEjaKgH42wxApFyJYGPDyFyac5RNIbGhiwtuTeuthRxJwL85lf1uoOrvCsT8y5CtQstyo9cd9rNDgDauKSooRmBxxffKv9wzbhpG329PM8P0ErhuOBheuxYprfzgHXuozVyvlw2S9G1DQzj4WtTIY51DkuasLZcSBjJsq2W/bwDwOyRDaMjI9WAWqWMNS3PR7H830oDTG8a+0CLg0B1miByVQbK7eyE0QKps=
    users:
      secure: dagipcGb5/nV2fo3k6jdw/BMu41zD1OeN49ywtd8PjZNGxjk1IfJPYlivtp1Ngv54n7oRIlx/G1k8Hh4NczOCgZZGTEL+Vaj/XE0EzngLjDRMPJKWopox3/Gns91TQMSbUKP8Qjp8U/0H31Ij6MI+FKW2Bjbad+z1qRqrj27X1CQ8UPakJ1RPrCxCHuAKZgXPC2i//ax4/TrzFn1+39metGP/8oaOXdxyZClOn+y/X0DPCKQvrhwuUJegQTBAgtMfTIVt20lDl+WDHFJGri1fgG4Q3sWoEl6QWj2EUqF7bP7OaS/09neBUzsJ3maJaZVDTC8J+rIFcAuQTd9EQ8tl5l0CnFwnl8Z00VrnGO2dpeLF30dTnBJLqLThcfCKcKfhGQ3F8OGmGTGAgIGBXQdxlppAtgMNNH8IS2kaDJWvc7ceLBi/y67dkG6M43+Y8Viko7GbK+zdw7ss269XuCY38LwmwuhQo/wlgPJZ1Cls01YVFJ2tmbKfReWu2PAgAe76EvjuMb3zlj/Zqv30FGR14axjN3T84FnGs+GhjNfiKPCUDpT6Zp1V0Qfr0oUV6uMgZQ+jMTLcGYR1GGFsfRYQOSH0xF8wczck6xUsaPZLqNIcXdPiSpSULWxw5bK/b5xALXmmd7BMXxmZyxxJxOqjuXrTidx4hjxTWhVXk2d/88=
