language: R

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: always
