
name: lintr

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  lintr:
    permissions:
      # for github/codeql-action/upload-sarif to upload SARIF results
      security-events: write
    uses: pdil/usmapdata/.github/workflows/lintr.yaml@master
    secrets: inherit
